version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  tox:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - restore_cache:
          keys:
            # Need this to invalidate cache when lock changes, see:
            # https://circleci.com/docs/caching
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # Add a cache key for the Poetry virtual environment
            - v1-poetry-{{ checksum "pyproject.toml" }}
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: .circleci/circle-ci-deps.txt
      - run:
          name: Run tests
          command: tox
      - save_cache:
          paths:
            - $HOME/.cache/pypoetry/virtualenvs
          key: v1-poetry-{{ checksum "pyproject.toml" }}

  publish:
    docker:
      - image: cimg/python:3.11.2
    steps:
          - checkout
          - python/install-packages:
              pkg-manager: pip
              pip-dependency-file: .circleci/circle-ci-deps.txt
          - run:
              name: Install dependencies
              command: poetry install
          - run:
              name: Publish package to PyPI
              command: poetry publish --build -u __token__ -p $POETRY_PYPI_TOKEN

# Helpful:
# https://circleci.com/docs/variables
# https://circleci.com/docs/configuration-reference
workflows:
  pr-tox:
    jobs:
      - tox

  merge-publish-pypi:
    when:
      # Publish to PYPI on merge to main
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - publish
